[package]
name = "day09"
version.workspace = true
edition.workspace = true

[[bin]]
name = "day09-p1"
path = "src/bin/p1.rs"

[[bin]]
name = "day09-p2"
path = "src/bin/p2.rs"

[dependencies]
common = { path = "../common" }

# Add day-specific dependencies here
